name: SonarCloud Analysis

on:
  push:
    branches:
      - main  # Trigger on push to main branch. Change if your default branch is different.
  pull_request:
    branches:
      - main  # Trigger on pull request to main branch. Change if necessary.

jobs:
  sonarcloud:
    name: Analyze with SonarCloud
    runs-on: ubuntu-latest  # You can also use other operating systems like macOS or Windows.

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v3  # Check out the code from the repository.

    # Step 2: Set up JDK (for Java-based projects; if you use a different language, skip this step)
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adoptopenjdk'

    # Step 3: Cache SonarCloud dependencies (optional, but speeds up future builds)
    - name: Cache SonarCloud
      uses: actions/cache@v3
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar-${{ hashFiles('**/*.java', '**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-sonar-

    # Step 4: Run SonarCloud Scan
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v2
      with:
        organization: your-sonarcloud-organization  # Replace with your SonarCloud organization name
        token: ${{ secrets.SONAR_TOKEN }}  # Use the secret you created for the SonarCloud token
